# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170116_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
    ]
