# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170117_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.CharField(max_length=100000),
        ),
    ]
